#!/usr/bin/env node
// GENERATED tool — run via `node tools/generateIdentifierUnion.mjs`
// Reads every data/prompts/prompts-*.json in the repo, collects the union of
// all truthy identifierMap values across all prompts[] entries, then writes
// src/generated/identifierUnion.ts so the baked union is available in the
// npm tarball (which strips data/ via .npmignore).

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const repoRoot = path.resolve(__dirname, '..');
const promptsDir = path.join(repoRoot, 'data', 'prompts');
const outFile = path.join(repoRoot, 'src', 'generated', 'identifierUnion.ts');

function buildUnion(promptsDir) {
  const union = new Set();
  let files;
  try {
    files = fs.readdirSync(promptsDir);
  } catch {
    return union;
  }
  for (const name of files) {
    if (!name.startsWith('prompts-') || !name.endsWith('.json')) continue;
    try {
      const text = fs.readFileSync(path.join(promptsDir, name), 'utf8');
      const parsed = JSON.parse(text);
      for (const prompt of parsed.prompts ?? []) {
        for (const value of Object.values(prompt.identifierMap ?? {})) {
          if (value) union.add(value);
        }
      }
    } catch {
      // Skip unreadable/malformed files — a partial union still guards the
      // names it could load.
    }
  }
  return union;
}

const union = buildUnion(promptsDir);
const sorted = [...union].sort();

const lines = [
  '// GENERATED by tools/generateIdentifierUnion.mjs — do not edit',
  '/* eslint-disable */',
  '',
  `export const IDENTIFIER_UNION: readonly string[] = [`,
  ...sorted.map(name => `  ${JSON.stringify(name)},`),
  `];`,
  '',
];

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, lines.join('\n'), 'utf8');
console.log(
  `generateIdentifierUnion: wrote ${sorted.length} names to src/generated/identifierUnion.ts`
);
